# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "BuzzWatch.xcodeproj")
    build_app(scheme: "BuzzWatch Watch App", destination: "generic/platform=watchOS")
    upload_to_testflight(app_identifier: "com.evergreenlabs.BuzzWatch2", uses_non_exempt_encryption: false, skip_waiting_for_build_processing: true)
  end
end
